coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "header, diff, files"
  require_changes: true

ignore:
  - "**/*_test.go"
  - "pkg/version/*.go"
  - "cmd/**/*.go"
