
# Audio configuration
audio:
  - id: 101
    description: "16kbps AAC mono audio profile"
    codec: "aac"
    audio_bitrate: 16000
    channel_layout: "mono"

  - id: 102
    description: "32kbps AAC stereo audio profile"
    codec: "aac"
    audio_bitrate: 32000
    channel_layout: "stereo"

  - id: 103
    description: "64kbps AAC stereo audio profile"
    codec: "aac"
    audio_bitrate: 64000
    channel_layout: "stereo"

  - id: 104
    description: "128kbps AAC stereo audio profile"
    codec: "aac"
    audio_bitrate: 128000
    channel_layout: "stereo"

# Video configuration
video:
  - id: 201
    description: "540p H.264 video profile"
    codec: "libx264"
    video_bitrate: 2000000
    profile: high
    width: 960
    height: 540
    pixel_format: yuv420p
    options:
      preset: veryslow

# Format configuration
format:
  - id: 301
    name: hls-vod
    description: "HLS, video-on-demand, 4s segments"
    options:
      hls_time: 4
      hls_playlist_type: vod
      hls_flags: independent_segments
      g: 100
      keyint_min: 100
      sc_threshold: 0
