name: "Run tests on merge to main"
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: ["1.25", "1.26"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: |
          sudo apt -y update && sudo apt -y install nasm libde265-dev libaom-dev libdav1d-dev libxml2-dev liblzma-dev
          make test
